name: uttt_website
description: An absolute bare-bones web app.
# version: 1.0.0
#homepage: https://www.example.com
#author: moserd <email@example.com>

environment:
  sdk: '>=2.0.0'

dev_dependencies:
  build_runner: any
  build_web_compilers: any
  json_serializable: any

dependencies:
  js: any
  uttt_package:
    path: ../uttt_package
  json_annotation: any
  chartjs:
    git: https://github.com/google/chartjs.dart.git
  platform_detect: any

