name: uttt_package
description: A package, which provides usefull stuff for programming a Ultimate Tic Tac Toe game
version: 0.0.2
#homepage: https://www.example.com
#author: moserd <email@example.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  build_runner: any
  json_serializable: any

dev_dependencies:
  test: any
  json_annotation: any
  build_web_compilers: any
