import 'dart:convert';

import "package:test/test.dart";
import 'package:uttt_package/src/controller/GameStateController.dart';
import 'package:uttt_package/src/model/GameState.dart';

void main() {
  group("Tests method isGameFinished", () {
    test("newGame", () {
      GameState newGameState = GameState();
      expect(isGameFinished(newGameState), false);
    });
    test("Nearly finished", () {
      GameState gameState = GameState.fromJson(json.decode('{"tiles":[{"tiles":[{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"X"}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}}],"state":{"state":"."}},{"tiles":[{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}}],"state":{"state":"."}},{"tiles":[{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"O"}},{"state":{"state":"."}},{"state":{"state":"O"}},{"state":{"state":"."}},{"state":{"state":"O"}},{"state":{"state":"."}},{"state":{"state":"X"}}],"state":{"state":"O"}},{"tiles":[{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}}],"state":{"state":"."}},{"tiles":[{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"X"}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"X"}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"X"}}],"state":{"state":"X"}},{"tiles":[{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"O"}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"O"}},{"state":{"state":"."}}],"state":{"state":"."}},{"tiles":[{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"X"}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}}],"state":{"state":"."}},{"tiles":[{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"X"}}],"state":{"state":"."}},{"tiles":[{"state":{"state":"O"}},{"state":{"state":"."}},{"state":{"state":"X"}},{"state":{"state":"."}},{"state":{"state":"O"}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"O"}}],"state":{"state":"O"}}],"lastMove":{"state":{"state":"O"},"xBigTile":2,"yBigTile":2,"xTile":0,"yTile":0}}'));
      expect(isGameFinished(gameState), false);
    });
    test("Some moves played", () {
      GameState gameState = GameState.fromJson(json.decode(
          '{"tiles":[{"tiles":[{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"X"}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}}],"state":{"state":"."}},{"tiles":[{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}}],"state":{"state":"."}},{"tiles":[{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"O"}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"O"}},{"state":{"state":"."}},{"state":{"state":"X"}}],"state":{"state":"."}},{"tiles":[{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}}],"state":{"state":"."}},{"tiles":[{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}}],"state":{"state":"."}},{"tiles":[{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"O"}},{"state":{"state":"."}}],"state":{"state":"."}},{"tiles":[{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"X"}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}}],"state":{"state":"."}},{"tiles":[{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}}],"state":{"state":"."}},{"tiles":[{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"X"}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"O"}}],"state":{"state":"."}}],"lastMove":{"state":{"state":"O"},"xBigTile":2,"yBigTile":1,"xTile":1,"yTile":2}}'));
      expect(isGameFinished(gameState), false);
    });
    test("Finished", () {
      GameState gameState = GameState.fromJson(json.decode(
          '{"tiles":[{"tiles":[{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"X"}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"X"}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}}],"state":{"state":"."}},{"tiles":[{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}}],"state":{"state":"."}},{"tiles":[{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"O"}},{"state":{"state":"."}},{"state":{"state":"O"}},{"state":{"state":"."}},{"state":{"state":"O"}},{"state":{"state":"."}},{"state":{"state":"X"}}],"state":{"state":"O"}},{"tiles":[{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}}],"state":{"state":"."}},{"tiles":[{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"X"}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"X"}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"X"}}],"state":{"state":"X"}},{"tiles":[{"state":{"state":"."}},{"state":{"state":"O"}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"O"}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"O"}},{"state":{"state":"."}}],"state":{"state":"O"}},{"tiles":[{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"X"}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}}],"state":{"state":"."}},{"tiles":[{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"X"}}],"state":{"state":"."}},{"tiles":[{"state":{"state":"O"}},{"state":{"state":"."}},{"state":{"state":"X"}},{"state":{"state":"."}},{"state":{"state":"O"}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"O"}}],"state":{"state":"O"}}],"lastMove":{"state":{"state":"O"},"xBigTile":2,"yBigTile":1,"xTile":1,"yTile":0}}'));
      expect(isGameFinished(gameState), true);
    });
  });
  group("getAllPossibleMoves", () {
    test("newGame", () {
      GameState newGameState = GameState();
      expect(getAllPossibleMoves(newGameState).length, 81);
    });
    test("BigTile already won", () {
      GameState gameState = GameState.fromJson(json.decode(
          '{"tiles":[{"tiles":[{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"X"}}],"state":{"state":"."}},{"tiles":[{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"X"}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}}],"state":{"state":"."}},{"tiles":[{"state":{"state":"."}},{"state":{"state":"O"}},{"state":{"state":"O"}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"X"}}],"state":{"state":"."}},{"tiles":[{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}}],"state":{"state":"."}},{"tiles":[{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"X"}}],"state":{"state":"."}},{"tiles":[{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"O"}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}}],"state":{"state":"."}},{"tiles":[{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"X"}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}}],"state":{"state":"."}},{"tiles":[{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"X"}}],"state":{"state":"."}},{"tiles":[{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"X"}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"O"}},{"state":{"state":"O"}},{"state":{"state":"O"}}],"state":{"state":"O"}}],"lastMove":{"state":{"state":"X"},"xBigTile":1,"yBigTile":2,"xTile":2,"yTile":2}}'));
      expect(getAllPossibleMoves(gameState).length, 63);
    });
    test("Some moves played", () {
      GameState gameState = GameState.fromJson(json.decode(
          '{"tiles":[{"tiles":[{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"X"}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}}],"state":{"state":"."}},{"tiles":[{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}}],"state":{"state":"."}},{"tiles":[{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"O"}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"O"}},{"state":{"state":"."}},{"state":{"state":"X"}}],"state":{"state":"."}},{"tiles":[{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}}],"state":{"state":"."}},{"tiles":[{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}}],"state":{"state":"."}},{"tiles":[{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"O"}},{"state":{"state":"."}}],"state":{"state":"."}},{"tiles":[{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"X"}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}}],"state":{"state":"."}},{"tiles":[{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}}],"state":{"state":"."}},{"tiles":[{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"X"}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"O"}}],"state":{"state":"."}}],"lastMove":{"state":{"state":"O"},"xBigTile":2,"yBigTile":1,"xTile":1,"yTile":2}}'));
      List<Move> moves = [
        Move.fromJson(json.decode('{"state":{"state":"X"},"xBigTile":1,"yBigTile":2,"xTile":1,"yTile":0}')),
        Move.fromJson(json.decode('{"state":{"state":"X"},"xBigTile":1,"yBigTile":2,"xTile":0,"yTile":1}')),
        Move.fromJson(json.decode('{"state":{"state":"X"},"xBigTile":1,"yBigTile":2,"xTile":2,"yTile":1}')),
        Move.fromJson(json.decode('{"state":{"state":"X"},"xBigTile":1,"yBigTile":2,"xTile":1,"yTile":2}')),
        Move.fromJson(json.decode('{"state":{"state":"X"},"xBigTile":1,"yBigTile":2,"xTile":0,"yTile":0}')),
        Move.fromJson(json.decode('{"state":{"state":"X"},"xBigTile":1,"yBigTile":2,"xTile":2,"yTile":0}')),
        Move.fromJson(json.decode('{"state":{"state":"X"},"xBigTile":1,"yBigTile":2,"xTile":0,"yTile":2}')),
        Move.fromJson(json.decode('{"state":{"state":"X"},"xBigTile":1,"yBigTile":2,"xTile":2,"yTile":2}')),
        Move.fromJson(json.decode('{"state":{"state":"X"},"xBigTile":1,"yBigTile":2,"xTile":1,"yTile":1}')),
      ];
      expect(getAllPossibleMoves(gameState), moves);
    });
    test("Finished", () {
      GameState gameState = GameState.fromJson(json.decode(
          '{"tiles":[{"tiles":[{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"X"}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"X"}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}}],"state":{"state":"."}},{"tiles":[{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}}],"state":{"state":"."}},{"tiles":[{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"O"}},{"state":{"state":"."}},{"state":{"state":"O"}},{"state":{"state":"."}},{"state":{"state":"O"}},{"state":{"state":"."}},{"state":{"state":"X"}}],"state":{"state":"O"}},{"tiles":[{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}}],"state":{"state":"."}},{"tiles":[{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"X"}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"X"}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"X"}}],"state":{"state":"X"}},{"tiles":[{"state":{"state":"."}},{"state":{"state":"O"}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"O"}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"O"}},{"state":{"state":"."}}],"state":{"state":"O"}},{"tiles":[{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"X"}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}}],"state":{"state":"."}},{"tiles":[{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"X"}}],"state":{"state":"."}},{"tiles":[{"state":{"state":"O"}},{"state":{"state":"."}},{"state":{"state":"X"}},{"state":{"state":"."}},{"state":{"state":"O"}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"O"}}],"state":{"state":"O"}}],"lastMove":{"state":{"state":"O"},"xBigTile":2,"yBigTile":1,"xTile":1,"yTile":0}}'));
      expect(getAllPossibleMoves(gameState).length, 0);
    });
  });
  group("playMove", () {
    test("newGame", () {
      GameState newGame = GameState();
      playMove(newGame, Move.ofIndex(State.p1, 6, 8));
      GameState comparable = GameState();
      comparable.tiles[6].tiles[8].state = State.p1;
      comparable.lastMove = Move.ofIndex(State.p1, 6, 8);
      expect(newGame, comparable);
    });
    test("win bigTile", () {
      GameState state = GameState.fromJson(json.decode(
          '{"tiles":[{"tiles":[{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"X"}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"X"}}],"state":{"state":"."}},{"tiles":[{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}}],"state":{"state":"."}},{"tiles":[{"state":{"state":"O"}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"O"}},{"state":{"state":"."}},{"state":{"state":"X"}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}}],"state":{"state":"."}},{"tiles":[{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"X"}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}}],"state":{"state":"."}},{"tiles":[{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}}],"state":{"state":"."}},{"tiles":[{"state":{"state":"O"}},{"state":{"state":"."}},{"state":{"state":"O"}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"O"}},{"state":{"state":"."}},{"state":{"state":"O"}}],"state":{"state":"."}},{"tiles":[{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"X"}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}}],"state":{"state":"."}},{"tiles":[{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}}],"state":{"state":"."}},{"tiles":[{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"X"}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"X"}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"O"}}],"state":{"state":"."}}],"lastMove":{"state":{"state":"O"},"xBigTile":2,"yBigTile":1,"xTile":0,"yTile":0}}'));
      expect(isGameFinished(state), false);
      Move move = Move(State.p1, 2, 0, 0, 0);
      playMove(state, move);
      expect(isGameFinished(state), false);
      expect(state.tiles[move.bigIndex].state, move.state);
      expect(state.tiles[move.bigIndex].tiles[move.smallIndex].state, move.state);
    });
    test("win game", () {
      GameState state = GameState.fromJson(json.decode(
          '{"tiles":[{"tiles":[{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"X"}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"X"}}],"state":{"state":"."}},{"tiles":[{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"X"}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}}],"state":{"state":"."}},{"tiles":[{"state":{"state":"O"}},{"state":{"state":"O"}},{"state":{"state":"O"}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"X"}}],"state":{"state":"O"}},{"tiles":[{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"X"}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}}],"state":{"state":"."}},{"tiles":[{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"X"}}],"state":{"state":"."}},{"tiles":[{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"O"}},{"state":{"state":"O"}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}}],"state":{"state":"."}},{"tiles":[{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"X"}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}}],"state":{"state":"."}},{"tiles":[{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"X"}}],"state":{"state":"."}},{"tiles":[{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"X"}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"."}},{"state":{"state":"O"}},{"state":{"state":"O"}},{"state":{"state":"O"}}],"state":{"state":"O"}}],"lastMove":{"state":{"state":"X"},"xBigTile":0,"yBigTile":1,"xTile":2,"yTile":1}}'));
      expect(isGameFinished(state), false);
      Move move = Move(State.p2, 2, 1, 2, 1);
      playMove(state, move);
      expect(isGameFinished(state), true);
      expect(state.tiles[move.bigIndex].state, move.state);
    });
  });
}